default[:opsworks_tcp_setup][:sysctl] = Mash.new
default[:opsworks_tcp_setup][:sysctl]['net.core.somaxconn'] = 65535           # 128
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_max_syn_backlog'] = 20480 # 1024
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_fin_timeout'] = 15       # 60
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_keepalive_time'] = 1024  # 7200
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_max_orphans'] = 131072   # 32768
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_tw_reuse'] = 1           # 0
default[:opsworks_tcp_setup][:sysctl]['net.core.rmem_max'] = 33554432
default[:opsworks_tcp_setup][:sysctl]['net.core.wmem_max'] = 33554432
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_mem'] = '786432 1048576 26777216'
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_max_tw_buckets'] = 360000
default[:opsworks_tcp_setup][:sysctl]['net.core.netdev_max_backlog'] = 65536
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_syn_retries'] = 2
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_synack_retries'] = 2
default[:opsworks_tcp_setup][:sysctl]['vm.min_free_kbytes'] = 65536
default[:opsworks_tcp_setup][:sysctl]['vm.swappiness'] = 0
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.ip_local_port_range'] = '1024 65535'
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait'] = 1
default[:opsworks_tcp_setup][:sysctl]['net.nf_conntrack_max'] = 1000000
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_retries2'] = 5
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_keepalive_probes']=2
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_keepalive_intvl'] = 5
default[:opsworks_tcp_setup][:sysctl]['fs.file-max'] = 2097152
default[:opsworks_tcp_setup][:sysctl]['net.core.rmem_default'] = 31457280
default[:opsworks_tcp_setup][:sysctl]['net.core.optmem_max'] = 25165824
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_rfc1337'] = 1
default[:opsworks_tcp_setup][:sysctl]['net.core.wmem_max'] = 12582912
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_rmem'] = "4096  16384 33554432"
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_wmem'] = "4096  16384 33554432"
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_tw_recycle'] = 0
default[:opsworks_tcp_setup][:sysctl]['net.ipv4.tcp_tw_reuse'] = 1
default[:opsworks_tcp_setup][:limits][:nofile] = 500000